development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username:
  password:
    
test: &TEST
  adapter: postgresql
  encoding: utf8
  database: zalbo_production
  host: localhost
  pool: 5
  username: zalbo_deployer
  password: ENV["password_db"]

production:
  adapter: postgresql
  encoding: utf8
  database: zalbo_production
  host: localhost
  pool: 5
  username: zalbo_deployer
  password: ENV["password_db"]

cucumber:
  <<: *TEST
