development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username:
  password:

production:
  <<: *default
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: zalbo_production
  pool: 5
  username: <%= ENV['ZALBO_DATABASE_USER'] %>
  password: <%= ENV['ZALBO_DATABASE_PASSWORD'] %>

cucumber:
  <<: *TEST
